### ISSUE TITLE
Example not working with AWS Account profile

### ISSUE THREAD

**Issue by trahloff** [cloudposse/terraform-aws-eks-fargate-profile#2] opened 2020-03-02 14:10 UTC
With the current setup, it is not possible to use this module with an AWS profile. Perhaps this is intended. If yes, feel free to see this as an FYI and close the issue. 

Using the example with an AWS profile: 

```
provider "aws" {
  region  = var.aws_region
  profile = local.aws_profile
}
```

```
Error: Error running command '      set -e

      install_aws_cli=false
      if [[ "$install_aws_cli" = true ]] ; then
          echo 'Installing AWS CLI...'
          mkdir -p .terraform/modules/eks_cluster/.terraform/bin
          cd .terraform/modules/eks_cluster/.terraform/bin
          curl -LO https://s3.amazonaws.com/aws-cli/awscli-bundle.zip
          unzip ./awscli-bundle.zip
          ./awscli-bundle/install -i .terraform/modules/eks_cluster/.terraform/bin
          export PATH=$PATH:.terraform/modules/eks_cluster/.terraform/bin:.terraform/modules/eks_cluster/.terraform/bin/bin
          echo 'Installed AWS CLI'
          which aws
          aws --version
      fi

      install_kubectl=false
      if [[ "$install_kubectl" = true ]] ; then
          echo 'Installing kubectl...'
          mkdir -p .terraform/modules/eks_cluster/.terraform/bin
          cd .terraform/modules/eks_cluster/.terraform/bin
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          export PATH=$PATH:.terraform/modules/eks_cluster/.terraform/bin
          echo 'Installed kubectl'
          which kubectl
      fi

      aws_cli_assume_role_arn=
      aws_cli_assume_role_session_name=
      if [[ -n "$aws_cli_assume_role_arn" && -n "$aws_cli_assume_role_session_name" ]] ; then
        echo 'Assuming role  ...'
        mkdir -p .terraform/modules/eks_cluster/.terraform/bin
        cd .terraform/modules/eks_cluster/.terraform/bin
        curl -L https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o jq
        chmod +x ./jq
        source <(aws --output json sts assume-role --role-arn "$aws_cli_assume_role_arn" --role-session-name "$aws_cli_assume_role_session_name"  | jq -r  '.Credentials | @sh "export AWS_SESSION_TOKEN=\(.SessionToken)\nexport AWS_ACCESS_KEY_ID=\(.AccessKeyId)\nexport AWS_SECRET_ACCESS_KEY=\(.SecretAccessKey) "')
        echo 'Assumed role '
      fi

      echo 'Applying Auth ConfigMap with kubectl...'
      aws eks update-kubeconfig --name=eg-test-eks-fargate-cluster --region=eu-west-1 --kubeconfig=/.kube/config 
      kubectl version --kubeconfig /.kube/config
      kubectl apply -f .terraform/modules/eks_cluster/configmap-auth.yaml --kubeconfig /.kube/config
      echo 'Applied Auth ConfigMap with kubectl'
': exit status 255. Output: Applying Auth ConfigMap with kubectl...

An error occurred (ResourceNotFoundException) when calling the DescribeCluster operation: No cluster found for name: eg-test-eks-fargate-cluster.
```

**Comment by derjohn** [comment] 2020-12-25 10:42
Hello,
you can "export AWS_DEFAULT_PROFILE=xxxx". The terraform aws provider supports this. I think the kube.conf supports that too, because it calls aws-iam-authenticator (which is build upon the AWS sdk). 

I think the root of the issue is in auth.tf

```
provider "kubernetes" {
  token                  = join("", data.aws_eks_cluster_auth.eks.*.token)
  host                   = join("", data.aws_eks_cluster.eks.*.endpoint)
  cluster_ca_certificate = base64decode(join("", data.aws_eks_cluster.eks.*.certificate_authority.0.data))
  load_config_file       = var.kubernetes_load_config_file
  config_path            = var.kubernetes_config_path
}
```

Maybe in your setup you could also try not to set the kube_config path to /.kube/config (really on "/" ?).
Did you set kubernetes_load_config_file?

rgds,
derjohn

**Comment by Nuru** [comment] 2023-07-11 09:07
Closing because this is (a) not a bug in this module, (b) not really a bug in the example (it was a bug in `terraform-aws-eks-cluster`, and (c) fixed a long time ago, but because of (a) and (b), no one really noticed.

**Closed by Nuru** 2023-07-11 09:07 UTC
